// Fill out your copyright notice in the Description page of Project Settings.

#include "Nodes/CrowdyK2Node_ApplyEffectCallBase.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintFunctionNodeSpawner.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Editor.h"
#include "K2Node_MakeMap.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Nodes/CrowdyApplyEffectNodePins.h"
#include "Nodes/CrowdyApplyEffectNodeShared.h"
#include "Replication/GameModel/CrowdyEffects.h"
#include "Replication/GameModel/Effect/CrowdyEffect.h"
#include "Replication/GameModel/Effect/CrowdyEffectLowering.h"
#include "TimerManager.h"
#include "UObject/UnrealType.h"
#include "UObject/UObjectGlobals.h"

#define LOCTEXT_NAMESPACE "CrowdyK2Node_ApplyEffectCallBase"

using namespace CrowdyApplyEffectNodeShared;

UCrowdyEffect* UCrowdyK2Node_ApplyEffectCallBase::GetLiteralEffect() const
{
	// Mid-rebuild, the live Effect pin is a freshly allocated one with no value yet (the value is only copied back
	// off the outgoing pin once pin allocation has returned), so the pending value captured in
	// ReallocatePinsDuringReconstruction is the only correct source of truth at that point.
	UCrowdyEffect* Effect = PendingReconstructionEffect;
	if (!Effect)
	{
		const UEdGraphPin* Pin = FindPin(PN_Effect, EGPD_Input);
		if (!Pin || Pin->LinkedTo.Num() > 0)
		{
			return nullptr;
		}
		Effect = Cast<UCrowdyEffect>(Pin->DefaultObject);
	}

	// Everything this node shapes itself from lives on the asset, and the asset can still be an unserialized export
	// while this graph is compiled on load, so no caller may read it before it is in.
	PreloadEffectAsset(Effect);
	return Effect;
}

void UCrowdyK2Node_ApplyEffectCallBase::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	// Pin allocation (run by Super below) rebuilds a brand new Effect pin with an empty DefaultObject, and the
	// outgoing pin's value is only copied onto it afterward. Read that value now, off the still intact OldPins, so
	// the reshape sees the effect that is actually about to be restored instead of treating the node as emptied out.
	PendingReconstructionEffect = nullptr;
	for (UEdGraphPin* OldPin : OldPins)
	{
		if (OldPin && OldPin->PinName == PN_Effect && OldPin->LinkedTo.Num() == 0)
		{
			PendingReconstructionEffect = Cast<UCrowdyEffect>(OldPin->DefaultObject);
			break;
		}
	}

	Super::ReallocatePinsDuringReconstruction(OldPins);

	PendingReconstructionEffect = nullptr;
}

void UCrowdyK2Node_ApplyEffectCallBase::AllocateDefaultPins()
{
	// A node placed from the Blueprint action menu is handed its function reference before its pins are built. One
	// created any other way still needs it, since every pin here comes from that function's signature.
	if (FunctionReference.GetMemberName().IsNone())
	{
		if (UFunction* Wrapped = GetWrappedFunction())
		{
			SetFromFunction(Wrapped);
		}
	}

	Super::AllocateDefaultPins();
	SynchronizeEffectPins();
	RegisterEffectAssetListener();
}

void UCrowdyK2Node_ApplyEffectCallBase::PostReconstructNode()
{
	Super::PostReconstructNode();

	// A rebuild carries a designer-set value from the old pin onto the new one, hidden or not. Re-hiding here, after
	// that copy has happened, is what stops a Source or Level the effect no longer uses from reaching the call.
	ApplyParameterPinVisibility();
}

void UCrowdyK2Node_ApplyEffectCallBase::ApplyParameterPinVisibility()
{
	UCrowdyEffect* Effect = GetLiteralEffect();
	const bool bHasLiteralEffect = Effect != nullptr;
	const FCrowdyApplyEffectPinPlan Plan = CrowdyApplyEffectNodePins::BuildPinPlan(Effect);

	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();

	for (UEdGraphPin* Pin : Pins)
	{
		if (!Pin || Pin->Direction != EGPD_Input)
		{
			continue;
		}
		if (ActionForParameterPin(Pin->PinName, Plan, bHasLiteralEffect) != EParameterPinAction::HideAndReset)
		{
			continue;
		}

		Pin->bHidden = true;
		if (Schema)
		{
			Schema->ResetPinToAutogeneratedDefaultValue(Pin, false);
		}
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::SynchronizeEffectPins()
{
	ApplyParameterPinVisibility();

	UCrowdyEffect* Effect = GetLiteralEffect();
	if (!Effect)
	{
		// No literal effect: leave the plain pin set, with the raw Overrides map visible. ExpandNode and
		// ValidateNodeDuringCompilation detect this same state and degrade accordingly.
		return;
	}

	const FCrowdyApplyEffectPinPlan Plan = CrowdyApplyEffectNodePins::BuildPinPlan(Effect);
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();

	for (const FCrowdyApplyEffectPinEntry& Entry : Plan.Magnitudes)
	{
		UEdGraphPin* Pin = CreatePin(EGPD_Input, MagnitudePinType(Entry.ValueType), Entry.PinName);
		Pin->PinFriendlyName = FText::FromString(Entry.MagnitudeName);
		CrowdyApplyEffectNodePins::ApplyMagnitudeDefaultToPin(Pin, Entry, Schema);
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::RemoveMagnitudePins()
{
	TArray<UEdGraphPin*> MagnitudePins;
	for (UEdGraphPin* Pin : Pins)
	{
		if (Pin && ShouldRemovePinBeforeCall(Pin->PinName))
		{
			MagnitudePins.Add(Pin);
		}
	}
	for (UEdGraphPin* Pin : MagnitudePins)
	{
		RemovePin(Pin);
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	// A new effect asset reshapes the whole magnitude pin set. Rebuilding here would tear down this pin set
	// immediately, but the caller that set the value keeps dereferencing the changed pin after this returns, so
	// freeing it now is a use-after-free. Defer the rebuild until that call has fully unwound.
	if (Pin && Pin->PinName == PN_Effect)
	{
		ScheduleReconstruct();
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::ScheduleReconstruct()
{
	if (bReconstructPending || !GEditor)
	{
		return;
	}
	bReconstructPending = true;

	// A next-tick timer runs once the current input event has fully unwound, so the pin the picker still holds is no
	// longer live when the rebuild destroys it. Weak-bound: a node deleted before the tick fires does nothing.
	GEditor->GetTimerManager()->SetTimerForNextTick(FTimerDelegate::CreateWeakLambda(this, [this]()
	{
		bReconstructPending = false;
		ReconstructNode();
		if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
		{
			FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);
		}
	}));
}

void UCrowdyK2Node_ApplyEffectCallBase::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);

	// Wiring or unwiring the Effect pin flips between the typed and the plain pin sets.
	if (Pin && Pin->PinName == PN_Effect)
	{
		ReconstructNode();
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::PostPlacedNewNode()
{
	Super::PostPlacedNewNode();
	RegisterEffectAssetListener();
}

void UCrowdyK2Node_ApplyEffectCallBase::PostLoad()
{
	Super::PostLoad();
	RegisterEffectAssetListener();
}

void UCrowdyK2Node_ApplyEffectCallBase::BeginDestroy()
{
	if (OnPropertyChangedHandle.IsValid())
	{
		FCoreUObjectDelegates::OnObjectPropertyChanged.Remove(OnPropertyChangedHandle);
		OnPropertyChangedHandle.Reset();
	}
	Super::BeginDestroy();
}

void UCrowdyK2Node_ApplyEffectCallBase::RegisterEffectAssetListener()
{
	// Only real graph nodes need to react to asset edits; template nodes built for the action menu have no graph and
	// would only add a needless global-delegate subscription.
	if (!GetGraph())
	{
		return;
	}
	if (!OnPropertyChangedHandle.IsValid())
	{
		OnPropertyChangedHandle = FCoreUObjectDelegates::OnObjectPropertyChanged.AddUObject(
			this, &UCrowdyK2Node_ApplyEffectCallBase::HandleObjectPropertyChanged);
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::HandleObjectPropertyChanged(UObject* Object,
	FPropertyChangedEvent& PropertyChangedEvent)
{
	// React only to edits on the effect this node references; any other asset's change is irrelevant.
	if (!Object || Object != GetLiteralEffect())
	{
		return;
	}

	// A slider drag fires a stream of interactive changes; skip them and rebuild once when the final committed
	// change lands, so mid-drag churn does not thrash the whole node.
	if (PropertyChangedEvent.ChangeType == EPropertyChangeType::Interactive)
	{
		return;
	}

	// Only an edit to a field the pin layout is built from needs a rebuild.
	if (!ChangeAffectsPinPlan(PropertyChangedEvent))
	{
		return;
	}

	ReconstructNode();
}

FText UCrowdyK2Node_ApplyEffectCallBase::GetBaseNodeTitle() const
{
	return LOCTEXT("BaseNodeTitle", "Apply Crowdy Effect");
}

FText UCrowdyK2Node_ApplyEffectCallBase::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (const UCrowdyEffect* Effect = GetLiteralEffect())
	{
		return FText::Format(LOCTEXT("NodeTitleWithEffect", "{0}: {1}"),
			GetBaseNodeTitle(), FText::FromString(Effect->GetName()));
	}
	return GetBaseNodeTitle();
}

FText UCrowdyK2Node_ApplyEffectCallBase::GetMenuCategory() const
{
	return LOCTEXT("MenuCategory", "Crowdy SDK|Game Model|Effects");
}

void UCrowdyK2Node_ApplyEffectCallBase::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (!ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		return;
	}

	UFunction* Wrapped = GetWrappedFunction();
	if (!Wrapped)
	{
		return;
	}

	// Spawning through the function spawner is what hands the placed node its function reference, so the pins it
	// builds come from the real signature rather than from anything restated here.
	UBlueprintFunctionNodeSpawner* Spawner = UBlueprintFunctionNodeSpawner::Create(GetClass(), Wrapped);
	check(Spawner);

	ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
}

void UCrowdyK2Node_ApplyEffectCallBase::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	// Checked before the Effect diagnostics below, which return early: an unwired Target on a non-container
	// Blueprint is wrong regardless of what the Effect pin holds. The by-id subclass has no Target pin, and the
	// helper treats an absent pin as nothing to judge.
	CrowdyApplyEffectNodeShared::ValidateSelfTargetIsContainer(
		this, FindPin(CrowdyApplyEffectNodeShared::PN_Target, EGPD_Input), MessageLog);

	const UEdGraphPin* EffectPin = FindPin(PN_Effect, EGPD_Input);
	if (EffectPin && EffectPin->LinkedTo.Num() > 0)
	{
		MessageLog.Warning(*LOCTEXT("ConnectedEffect",
			"@@ has a connected Effect pin, so its magnitudes can't be read at compile time. It falls back to a raw "
			"Overrides map. Set the Effect as a literal to get typed magnitude pins.").ToString(), this);
		return;
	}

	UCrowdyEffect* Effect = GetLiteralEffect();
	if (!Effect)
	{
		MessageLog.Error(*LOCTEXT("MissingEffect", "@@ has no Effect assigned.").ToString(), this);
		return;
	}

	// A malformed effect (parse / lowering error) would silently apply nothing; surface it here so the graph fails to
	// compile rather than at runtime. Compiled without the fn-callee catalog: only Error diagnostics are surfaced
	// here, the catalog adds warnings alone, and a catalog cache miss would force-load every Crowdy Effect asset in
	// the middle of a Blueprint compile.
	const FCrowdyEffectLoweringResult Lowered = Effect->Compile(ECrowdyEffectFnCatalog::None);
	if (Lowered.HasErrors())
	{
		MessageLog.Error(*FText::Format(LOCTEXT("EffectCompileFailed",
			"@@ references effect '{0}', which does not compile ({1}). Fix it in the effect asset."),
			FText::FromString(Effect->GetName()),
			FText::FromString(FirstCompileError(Lowered.Diagnostics))).ToString(), this);
	}

	const FCrowdyApplyEffectPinPlan Plan = CrowdyApplyEffectNodePins::BuildPinPlan(Effect);

	// A duplicated magnitude name collapses to one pin, so a second magnitude of that name would silently lose its
	// value. Fail compilation naming each duplicate rather than dropping it at runtime.
	for (const FString& Duplicate : Plan.DuplicateMagnitudeNames)
	{
		MessageLog.Error(*FText::Format(LOCTEXT("DuplicateMagnitudeName",
			"@@ references effect '{0}', which declares more than one magnitude named '{1}'. Give each magnitude a "
			"unique name."),
			FText::FromString(Effect->GetName()), FText::FromString(Duplicate)).ToString(), this);
	}

	// A required magnitude (no default, no curve) must be supplied: its pin must be wired or set to a value.
	for (const FCrowdyApplyEffectPinEntry& Entry : Plan.Magnitudes)
	{
		if (!Entry.bRequired)
		{
			continue;
		}
		const UEdGraphPin* Pin = FindPin(Entry.PinName, EGPD_Input);
		// A required pin is unsupplied when it is unwired and still sitting at its autogenerated default. This uses
		// the pin's own change-detection rather than an empty-string test: a numeric pin carries a valid non-empty
		// default, so "empty" is not the right signal for "untouched".
		const bool bUnset = Pin && Pin->LinkedTo.Num() == 0
			&& (Entry.IsContainerRef() ? (Pin->DefaultObject == nullptr) : Pin->DoesDefaultValueMatchAutogenerated());
		if (!Pin || bUnset)
		{
			MessageLog.Error(*FText::Format(LOCTEXT("RequiredMagnitudeEmpty",
				"@@ requires a value for magnitude '{0}' (the effect gives it no default)."),
				FText::FromString(Entry.MagnitudeName)).ToString(), this);
		}
	}
}

void UCrowdyK2Node_ApplyEffectCallBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	UCrowdyEffect* Effect = GetLiteralEffect();
	if (Effect)
	{
		const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
		check(Schema);
		bool bIsErrorFree = true;

		UEdGraphPin* OverridesPin = FindPin(PN_Overrides, EGPD_Input);

		// Collect the magnitude pins that actually contribute an Override: wired, or changed from their prefill.
		struct FIncluded
		{
			UEdGraphPin* Pin = nullptr;
			ECrowdyEffectValueType ValueType = ECrowdyEffectValueType::Int;
		};
		TArray<FIncluded> Included;
		TArray<FString> IncludedKeys;

		const FCrowdyApplyEffectPinPlan Plan = CrowdyApplyEffectNodePins::BuildPinPlan(Effect);
		for (const FCrowdyApplyEffectPinEntry& Entry : Plan.Magnitudes)
		{
			UEdGraphPin* Pin = FindPin(Entry.PinName, EGPD_Input);
			if (!Pin)
			{
				continue;
			}
			const bool bConnected = Pin->LinkedTo.Num() > 0;
			if (CrowdyApplyEffectNodePins::ShouldIncludeOverride(bConnected, Entry.IsContainerRef(), Pin->DefaultObject,
				Pin->DefaultValue, Pin->AutogeneratedDefaultValue))
			{
				Included.Add({ Pin, Entry.ValueType });
				IncludedKeys.Add(Entry.MagnitudeName);
			}
		}

		if (Included.Num() > 0 && OverridesPin)
		{
			UK2Node_MakeMap* MakeMap = CompilerContext.SpawnIntermediateNode<UK2Node_MakeMap>(this, SourceGraph);
			MakeMap->NumInputs = Included.Num();
			MakeMap->AllocateDefaultPins();

			// Force the map type to match the Overrides parameter rather than relying on wildcard propagation.
			if (UEdGraphPin* MapOut = MakeMap->GetOutputPin())
			{
				MapOut->PinType = OverridesPin->PinType;
			}

			TArray<UEdGraphPin*> KeyPins;
			TArray<UEdGraphPin*> ValuePins;
			MakeMap->GetKeyAndValuePins(KeyPins, ValuePins);

			for (int32 Index = 0; Index < Included.Num(); ++Index)
			{
				UEdGraphPin* KeyPin = KeyPins.IsValidIndex(Index) ? KeyPins[Index] : nullptr;
				UEdGraphPin* ValuePin = ValuePins.IsValidIndex(Index) ? ValuePins[Index] : nullptr;
				if (!KeyPin || !ValuePin)
				{
					bIsErrorFree = false;
					continue;
				}

				KeyPin->PinType.ResetToDefaults();
				KeyPin->PinType.PinCategory = UEdGraphSchema_K2::PC_Name;
				KeyPin->DefaultValue = IncludedKeys[Index];

				ValuePin->PinType.ResetToDefaults();
				ValuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_String;

				FName InputParam;
				const FName EncoderName = EncoderFunctionName(Included[Index].ValueType, InputParam);

				UK2Node_CallFunction* Encoder =
					CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
				Encoder->FunctionReference.SetExternalMember(EncoderName, UCrowdyEffects::StaticClass());
				Encoder->AllocateDefaultPins();

				UEdGraphPin* EncoderInput = Encoder->FindPin(InputParam, EGPD_Input);
				UEdGraphPin* EncoderReturn = Encoder->GetReturnValuePin();
				if (!EncoderInput || !EncoderReturn)
				{
					bIsErrorFree = false;
					continue;
				}

				// Carry the magnitude pin's literal default across, then move any external connection onto the
				// encoder input (a connected pin's value wins over the copied literal at runtime).
				EncoderInput->DefaultValue = Included[Index].Pin->DefaultValue;
				EncoderInput->DefaultObject = Included[Index].Pin->DefaultObject;
				EncoderInput->DefaultTextValue = Included[Index].Pin->DefaultTextValue;
				bIsErrorFree &=
					CompilerContext.MovePinLinksToIntermediate(*Included[Index].Pin, *EncoderInput).CanSafeConnect();

				bIsErrorFree &= Schema->TryCreateConnection(EncoderReturn, ValuePin);
			}

			// Feed the assembled map into this node's own (hidden) Overrides pin, which is the argument the call
			// reads. Nothing relocates it afterward: this node is the call.
			bIsErrorFree &= Schema->TryCreateConnection(MakeMap->GetOutputPin(), OverridesPin);
		}

		if (!bIsErrorFree)
		{
			CompilerContext.MessageLog.Error(
				*LOCTEXT("ExpandError", "@@: could not assemble the effect's magnitude overrides.").ToString(), this);
		}
	}

	// The magnitude pins have been consumed. They match no parameter of the function being called, and a call node
	// carrying such a pin does not compile, so they have to be gone before the call is emitted.
	RemoveMagnitudePins();

	Super::ExpandNode(CompilerContext, SourceGraph);
}

#undef LOCTEXT_NAMESPACE
