// Fill out your copyright notice in the Description page of Project Settings.

#include "Nodes/CrowdyApplyEffectNodePins.h"

#include "Curves/CurveFloat.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Replication/GameModel/Effect/CrowdyEffectMagnitudeJson.h"

namespace CrowdyApplyEffectNodePins
{
	namespace
	{
		const FString MagnitudePrefix = TEXT("CrowdyMag_");

		// A magnitude is required (must be supplied at apply time) when it has no authored default AND no curve to
		// sample. A curve-bound magnitude always yields a value, and a bool always has a value, so neither is
		// required. This mirrors the marshaller's "empty default, no curve" rejection.
		bool IsMagnitudeRequired(const FCrowdyEffectMagnitude& Magnitude, ECrowdyEffectValueType ValueType)
		{
			if (Magnitude.Curve != nullptr)
			{
				return false;
			}
			if (ValueType == ECrowdyEffectValueType::Bool)
			{
				return false;
			}
			return Magnitude.DefaultValueJson.IsEmpty();
		}
	}

	FName MagnitudePinName(const FString& MagnitudeName)
	{
		return FName(*(MagnitudePrefix + MagnitudeName));
	}

	bool IsMagnitudePinName(FName PinName)
	{
		return PinName.ToString().StartsWith(MagnitudePrefix, ESearchCase::CaseSensitive);
	}

	FCrowdyApplyEffectPinPlan BuildPinPlan(const UCrowdyEffect* Effect)
	{
		FCrowdyApplyEffectPinPlan Plan;
		if (!Effect)
		{
			return Plan;
		}

		Plan.bIncludeSource = Effect->bRequiresSource;
		Plan.ReturnType = Effect->ReturnType;

		TSet<FString> SeenNames;
		for (const FCrowdyEffectMagnitude& Magnitude : Effect->Magnitudes)
		{
			if (Magnitude.Name.IsEmpty())
			{
				continue;
			}

			// A repeated name would emit two pins that resolve to the same Overrides key: the first pin wins and the
			// second's value is lost. Keep only the first, and record the name so the node can fail compilation.
			if (SeenNames.Contains(Magnitude.Name))
			{
				Plan.DuplicateMagnitudeNames.AddUnique(Magnitude.Name);
				continue;
			}
			SeenNames.Add(Magnitude.Name);

			const ECrowdyEffectValueType ValueType = UCrowdyEffect::ResolveMagnitudeValueType(Magnitude);

			if (Magnitude.Curve != nullptr)
			{
				Plan.bIncludeLevel = true;
			}

			FCrowdyApplyEffectPinEntry Entry;
			Entry.MagnitudeName = Magnitude.Name;
			Entry.PinName = MagnitudePinName(Magnitude.Name);
			Entry.ValueType = ValueType;
			Entry.bRequired = IsMagnitudeRequired(Magnitude, ValueType);

			// The pin default is the raw (editor) form of the authored JSON default: a plain number, true/false, or
			// unquoted text. A container_ref pin is an object reference, so it carries no string default.
			if (ValueType != ECrowdyEffectValueType::ContainerRef)
			{
				Entry.DefaultValue = CrowdyEffectMagnitudeJson::FromCanonicalJson(ValueType, Magnitude.DefaultValueJson);
			}

			Plan.Magnitudes.Add(MoveTemp(Entry));
		}

		return Plan;
	}

	bool ShouldIncludeOverride(bool bConnected, bool bIsContainerRef, const UObject* CurrentObject,
		const FString& CurrentDefault, const FString& PrefilledDefault)
	{
		if (bIsContainerRef)
		{
			return bConnected || CurrentObject != nullptr;
		}
		return bConnected || CurrentDefault != PrefilledDefault;
	}

	void ApplyMagnitudeDefaultToPin(UEdGraphPin* Pin, const FCrowdyApplyEffectPinEntry& Entry,
		const UEdGraphSchema_K2* Schema)
	{
		if (!Pin)
		{
			return;
		}
		if (!Entry.IsContainerRef() && !Entry.DefaultValue.IsEmpty())
		{
			Pin->DefaultValue = Entry.DefaultValue;
			Pin->AutogeneratedDefaultValue = Entry.DefaultValue;
		}
		else if (Schema)
		{
			Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
		}
	}
}
