// Fill out your copyright notice in the Description page of Project Settings.

#include "Nodes/CrowdyApplyEffectNodePins.h"

#include "Curves/CurveFloat.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Replication/GameModel/Effect/CrowdyEffectMagnitudeJson.h"

namespace CrowdyApplyEffectNodePins
{
	namespace
	{
		const FString MagnitudePrefix = TEXT("CrowdyMag_");

		// A magnitude must be supplied at apply time when it is marked required AND has no curve to sample: a curve
		// always yields a value, so the caller never has to. This mirrors the marshaller's own rejection.
		bool IsMagnitudeRequired(const FCrowdyEffectMagnitude& Magnitude)
		{
			if (Magnitude.Curve != nullptr)
			{
				return false;
			}
			return UCrowdyEffect::ResolveMagnitudeRequired(Magnitude);
		}
	}

	FName MagnitudePinName(const FString& MagnitudeName)
	{
		return FName(*(MagnitudePrefix + MagnitudeName));
	}

	bool IsMagnitudePinName(FName PinName)
	{
		return PinName.ToString().StartsWith(MagnitudePrefix, ESearchCase::CaseSensitive);
	}

	FCrowdyApplyEffectPinPlan BuildPinPlan(const UCrowdyEffect* Effect)
	{
		FCrowdyApplyEffectPinPlan Plan;
		if (!Effect)
		{
			return Plan;
		}

		Plan.bIncludeSource = Effect->bRequiresSource;
		Plan.ReturnType = Effect->ReturnType;

		TSet<FString> SeenNames;
		for (const FCrowdyEffectMagnitude& Magnitude : Effect->Magnitudes)
		{
			if (Magnitude.Name.IsEmpty())
			{
				continue;
			}

			// A repeated name would emit two pins that resolve to the same Overrides key: the first pin wins and the
			// second's value is lost. Keep only the first, and record the name so the node can fail compilation.
			if (SeenNames.Contains(Magnitude.Name))
			{
				Plan.DuplicateMagnitudeNames.AddUnique(Magnitude.Name);
				continue;
			}
			SeenNames.Add(Magnitude.Name);

			const ECrowdyEffectValueType ValueType = UCrowdyEffect::ResolveMagnitudeValueType(Magnitude);

			if (Magnitude.Curve != nullptr)
			{
				Plan.bIncludeLevel = true;
			}

			FCrowdyApplyEffectPinEntry Entry;
			Entry.MagnitudeName = Magnitude.Name;
			Entry.PinName = MagnitudePinName(Magnitude.Name);
			Entry.ValueType = ValueType;
			Entry.bRequired = IsMagnitudeRequired(Magnitude);

			// The pin default is the raw (editor) form of the authored JSON default: a plain number, true/false, or
			// unquoted text. A container_ref pin is an object reference, so it carries no string default, and a
			// required magnitude has no default to show: its pin stays at the type's autogenerated value, which is
			// what the node's unset detection reads as unsupplied.
			if (ValueType != ECrowdyEffectValueType::ContainerRef
				&& !UCrowdyEffect::ResolveMagnitudeRequired(Magnitude))
			{
				Entry.DefaultValue = CrowdyEffectMagnitudeJson::FromCanonicalJson(ValueType, Magnitude.DefaultValueJson);
			}

			Plan.Magnitudes.Add(MoveTemp(Entry));
		}

		return Plan;
	}

	bool ShouldIncludeOverride(bool bConnected, bool bIsContainerRef, const UObject* CurrentObject,
		const FString& CurrentDefault, const FString& PrefilledDefault)
	{
		if (bIsContainerRef)
		{
			return bConnected || CurrentObject != nullptr;
		}
		return bConnected || !CurrentDefault.Equals(PrefilledDefault, ESearchCase::CaseSensitive);
	}

	void ApplyMagnitudeDefaultToPin(UEdGraphPin* Pin, const FCrowdyApplyEffectPinEntry& Entry,
		const UEdGraphSchema_K2* Schema)
	{
		if (!Pin)
		{
			return;
		}
		if (!Entry.IsContainerRef() && !Entry.DefaultValue.IsEmpty())
		{
			Pin->DefaultValue = Entry.DefaultValue;
			Pin->AutogeneratedDefaultValue = Entry.DefaultValue;
		}
		else if (Schema)
		{
			Schema->SetPinAutogeneratedDefaultValueBasedOnType(Pin);
		}
	}

	TMap<FName, FString> CaptureCaseOnlyMagnitudeValues(const TArray<UEdGraphPin*>& OldPins)
	{
		TMap<FName, FString> Values;
		for (const UEdGraphPin* Pin : OldPins)
		{
			if (!Pin || Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_String || !IsMagnitudePinName(Pin->PinName))
			{
				continue;
			}
			const FString& Value = Pin->DefaultValue;
			if (Value.Equals(Pin->AutogeneratedDefaultValue, ESearchCase::CaseSensitive)
				|| !Value.Equals(Pin->AutogeneratedDefaultValue, ESearchCase::IgnoreCase))
			{
				continue;
			}
			Values.Add(Pin->PinName, Value);
		}
		return Values;
	}

	void RestoreCaseOnlyMagnitudeValues(const TMap<FName, FString>& Values, const TArray<UEdGraphPin*>& Pins)
	{
		for (UEdGraphPin* Pin : Pins)
		{
			const FString* Value = Pin ? Values.Find(Pin->PinName) : nullptr;
			if (!Value || Pin->PinType.PinCategory != UEdGraphSchema_K2::PC_String)
			{
				continue;
			}
			Pin->DefaultValue = *Value;
		}
	}
}
