#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "CrowdyContainerManifest.generated.h"

class UCrowdyEntitySubsystem;

/** One Game Model container a level's placed actors will bind at runtime: the row a pre-seed creates ahead of them. */
USTRUCT(BlueprintType)
struct CROWDYREPLICATION_API FCrowdyContainerManifestRow
{
	GENERATED_BODY()

	/** The container type name declared by the actor class or the component class. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString TypeName;

	/** The binding key the runtime ensure will ask for: the digest of the entity's NetID. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString BindingKey;

	/** Creation-only display name for the server row; the actor label, or label.component for a component container. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString DisplayName;

	/** Object path of the placed actor the row was derived from, for the Studio preview and orphan reports. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString SourceActor;

	/** The component's name when the container is a component container, empty for the actor's own container. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString SourceComponent;
};

/**
 * The Game Model containers a map's level-placed entities will bind, computed in the editor from the same identity
 * the runtime derives, so a row created from this manifest is the row those entities find. One asset per map,
 * regenerated by the scan; it cooks, so a session creator can apply it at runtime as well as Studio at edit time.
 */
UCLASS(BlueprintType, Category = "Crowdy SDK|Data", meta = (DisplayName = "Crowdy Container Manifest"))
class CROWDYREPLICATION_API UCrowdyContainerManifest : public UDataAsset
{
	GENERATED_BODY()

public:
	/** The long package name of the map the rows were scanned from. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString MapPackage;

	/** When the scan ran, ISO 8601, so a stale manifest is visible next to a map that changed since. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	FString ScannedAt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Crowdy SDK|Container Manifest")
	TArray<FCrowdyContainerManifestRow> Rows;

	/** The rows whose (TypeName, BindingKey) repeats an earlier row: two placements that would fight over one server row. */
	TArray<int32> FindDuplicateRows() const;

#if WITH_EDITOR
	virtual EDataValidationResult IsDataValid(FDataValidationContext& ValidationContext) const override;
#endif
};

/**
 * The binding keys a level-placed entity and its component containers ensure with, from the same inputs the runtime
 * uses. Both the editor scan and any runtime applier derive keys through these so the two can never drift.
 */
struct CROWDYREPLICATION_API FCrowdyContainerManifestKeys
{
	/** The actor's own NetID: an authored binding key when present, else the engine placement guid. */
	static FGuid ActorNetID(const FGuid& PlacementGuid, const FString& BindingKeyOverride);

	/** The binding key of the container an entity with NetID ensures. */
	static FString KeyForNetID(const FGuid& NetID);

	/** The binding key of a component container enrolled on an anchor entity, seeded exactly as RegisterSubParticipant seeds it. */
	static FString ComponentKey(const FGuid& AnchorNetID, const UClass* ComponentClass, const FString& InstanceTerm);
};
