// The Server Object type ck_exec_fixture's glue, generated by the Crowdy SDK from its definition. Regenerate it; do not edit.
// Your code goes in logic.rs, which implements Functions on CrowdyExecTestBossState.
#![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, unused_variables)]

mod logic;
mod types;

use ckx_sdk::prelude::*;
use std::collections::{BTreeMap, BTreeSet};
pub use types::*;

const CONTRACT: u64 = 1;
const OWNER_ONLY: bool = false;

/// The Server Functions, implemented in logic.rs. A new function appears here first.
pub trait Functions {
    fn echo_scalars(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestScalars) -> Result<CrowdyExecTestScalars>;
    fn echo_containers(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestContainers) -> Result<CrowdyExecTestContainers>;
    fn echo_engine(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestEngine) -> Result<CrowdyExecTestEngine>;
    fn echo_extras(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestExtras) -> Result<CrowdyExecTestExtras>;
    fn echo_keys(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestKeys) -> Result<CrowdyExecTestKeys>;
    fn echo_raw(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestRaw) -> Result<CrowdyExecTestRaw>;
    fn defaults(&mut self, ctx: &Ctx, call: &Call<'_>) -> Result<CrowdyExecTestScalars>;
    fn hit(&mut self, ctx: &Ctx, call: &Call<'_>, params: CrowdyExecTestHit) -> Result<()>;
    fn heal(&mut self, ctx: &Ctx, call: &Call<'_>) -> Result<()>;
    fn on_timer(&mut self, ctx: &Ctx, name: &str) -> Result<()> {
        Ok(())
    }
    fn on_topic(&mut self, ctx: &Ctx, msg: TopicMsg<'_>) -> Result<()> {
        Ok(())
    }
    fn on_presence(&mut self, ctx: &Ctx, presence: &Presence) -> Result<()> {
        Ok(())
    }
}

#[derive(Serialize, Deserialize, Default)]
pub struct ServerObject {
    state: CrowdyExecTestBossState,
    epoch: u64,
    seq: u64,
}

#[derive(Serialize)]
struct SnapshotOut<'a> {
    contract: u64,
    state: &'a CrowdyExecTestBossState,
}

#[derive(Deserialize)]
struct SnapshotIn {
    contract: u64,
    state: CrowdyExecTestBossState,
}

impl Hub for ServerObject {
    fn spawn(ctx: &Ctx, seed: &[u8]) -> Result<Self> {
        let state = if seed.is_empty() { <CrowdyExecTestBossState as Default>::default() } else { decode(seed)? };
        Self::check_watched(&state).map_err(|(field, why)| Error::new(&format!("bad_seed: {field}: the seed holds a value players cannot read: {why}")))?;
        Ok(Self { state, epoch: ctx.now_ms() as u64, seq: 0 })
    }

    fn load(ctx: &Ctx, snapshot: &[u8], _from_version: u64) -> Result<Self> {
        let saved: SnapshotIn = decode(snapshot)?;
        if saved.contract != CONTRACT {
            return Err(Error::new(&format!("the snapshot was written for contract {}, this code reads {}", saved.contract, CONTRACT)));
        }
        Ok(Self { state: saved.state, epoch: ctx.now_ms() as u64, seq: 0 })
    }

    fn persist(&mut self, _ctx: &Ctx) -> Result<Vec<u8>> {
        encode(&SnapshotOut { contract: CONTRACT, state: &self.state })
    }

    fn handle(&mut self, ctx: &Ctx, call: Call<'_>) -> Result<Vec<u8>> {
        match call.method {
            "read" => {
                authorize(ctx, &call, true)?;
                Self::check_watched(&self.state).map_err(unreadable)?;
                self.read_reply()
            }
            "echo_scalars" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestScalars = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_scalars(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "echo_containers" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestContainers = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_containers(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "echo_engine" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestEngine = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_engine(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "echo_extras" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestExtras = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_extras(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "echo_keys" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestKeys = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_keys(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "echo_raw" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestRaw = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::echo_raw(&mut self.state, ctx, &call, params).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "defaults" => {
                authorize(ctx, &call, true)?;
                let before = Clone::clone(&self.state);
                let result = Functions::defaults(&mut self.state, ctx, &call).and_then(|reply| encode_reply(&reply));
                self.finish(ctx, before, result)
            }
            "hit" => {
                authorize(ctx, &call, true)?;
                let params: CrowdyExecTestHit = call.decode().map_err(bad_params)?;
                Wire::check(&params).map_err(|why| Error::new(&format!("bad_params: {why}")))?;
                let before = Clone::clone(&self.state);
                let result = Functions::hit(&mut self.state, ctx, &call, params).map(|()| vec![0xc0]);
                self.finish(ctx, before, result)
            }
            "heal" => {
                authorize(ctx, &call, false)?;
                let before = Clone::clone(&self.state);
                let result = Functions::heal(&mut self.state, ctx, &call).map(|()| vec![0xc0]);
                self.finish(ctx, before, result)
            }
            other => Err(Error::new(&format!("unknown_method: {other}"))),
        }
    }

    fn on_timer(&mut self, ctx: &Ctx, name: &str) -> Result<()> {
        let before = Clone::clone(&self.state);
        let result = Functions::on_timer(&mut self.state, ctx, name);
        self.finish(ctx, before, result)
    }

    fn on_topic(&mut self, ctx: &Ctx, msg: TopicMsg<'_>) -> Result<()> {
        let before = Clone::clone(&self.state);
        let result = Functions::on_topic(&mut self.state, ctx, msg);
        self.finish(ctx, before, result)
    }

    fn on_presence(&mut self, ctx: &Ctx, presence: &Presence) -> Result<()> {
        let before = Clone::clone(&self.state);
        let result = Functions::on_presence(&mut self.state, ctx, presence);
        self.finish(ctx, before, result)
    }
}

impl ServerObject {
    // A failed dispatch, or a change that could not be sent, leaves the state as it was and publishes nothing.
    fn finish<T>(&mut self, ctx: &Ctx, before: CrowdyExecTestBossState, result: Result<T>) -> Result<T> {
        // Everything that can fail runs before the change is kept and pushed.
        let prepared = result.and_then(|value| {
            let push = self.prepare_push(&before)?;
            Ok((value, push))
        });
        let (value, push) = match prepared {
            Ok(prepared) => prepared,
            Err(error) => {
                self.state = before;
                return Err(error);
            }
        };
        if let Some(out) = push {
            self.seq += 1;
            let _ = ctx.publish("state", &out);
        }
        Ok(value)
    }

    // The first watched value an Unreal client could not read, with the field it is in.
    fn check_watched(state: &CrowdyExecTestBossState) -> std::result::Result<(), (&'static str, &'static str)> {
        Wire::check(&state.Health).map_err(|why| ("Health", why))?;
        Wire::check(&state.bDefeated).map_err(|why| ("bDefeated", why))?;
        Wire::check(&state.Phase).map_err(|why| ("Phase", why))?;
        Ok(())
    }

    fn read_reply(&self) -> Result<Vec<u8>> {
        let mut out = Vec::new();
        write_map(&mut out, 4);
        write_str(&mut out, "contract");
        write_uint(&mut out, CONTRACT);
        write_str(&mut out, "epoch");
        write_uint(&mut out, self.epoch);
        write_str(&mut out, "seq");
        write_uint(&mut out, self.seq);
        write_str(&mut out, "fields");
        write_map(&mut out, 3);
        write_field(&mut out, "Health", &self.state.Health)?;
        write_field(&mut out, "bDefeated", &self.state.bDefeated)?;
        write_field(&mut out, "Phase", &self.state.Phase)?;
        Ok(out)
    }

    fn prepare_push(&self, before: &CrowdyExecTestBossState) -> Result<Option<Vec<u8>>> {
        let mut changed: Vec<(&str, Vec<u8>)> = Vec::new();
        if self.state.Health != before.Health {
            Wire::check(&self.state.Health).map_err(|why| unsendable("Health", why))?;
            changed.push(("Health", encode(&self.state.Health)?));
        }
        if self.state.bDefeated != before.bDefeated {
            Wire::check(&self.state.bDefeated).map_err(|why| unsendable("bDefeated", why))?;
            changed.push(("bDefeated", encode(&self.state.bDefeated)?));
        }
        if self.state.Phase != before.Phase {
            Wire::check(&self.state.Phase).map_err(|why| unsendable("Phase", why))?;
            changed.push(("Phase", encode(&self.state.Phase)?));
        }
        if changed.is_empty() {
            return Ok(None);
        }
        // A push carries a subset of what a read carries, so a read that fits means the push fits too.
        if self.read_reply()?.len() > MAX_MESSAGE {
            return Err(unsendable("the watched values", "together they are larger than 1 MiB"));
        }
        let mut out = Vec::new();
        write_map(&mut out, if OWNER_ONLY { 2 } else { 3 });
        write_str(&mut out, "epoch");
        write_uint(&mut out, self.epoch);
        write_str(&mut out, "seq");
        write_uint(&mut out, self.seq + 1);
        if !OWNER_ONLY {
            write_str(&mut out, "fields");
            write_map(&mut out, changed.len());
            for (name, bytes) in &changed {
                write_str(&mut out, name);
                out.extend_from_slice(bytes);
            }
        }
        Ok(Some(out))
    }
}

// Players may call only player-callable functions, and on an owner-only type only the owner; developer tools and other
// server code may call everything.
fn authorize(ctx: &Ctx, call: &Call<'_>, player_callable: bool) -> Result<()> {
    let Ok(player) = call.player() else {
        return Ok(());
    };
    if !player_callable {
        return Err(Error::new("denied: players may not call this function"));
    }
    if OWNER_ONLY && player.to_string() != ctx.key {
        return Err(Error::new("denied: only the owner may use this Server Object"));
    }
    Ok(())
}

fn bad_params(error: Error) -> Error {
    let text = error.to_string();
    Error::new(&format!("bad_params: {}", text.strip_prefix("decode: ").unwrap_or(&text)))
}

fn write_field<T: Serialize>(out: &mut Vec<u8>, name: &str, value: &T) -> Result<()> {
    write_str(out, name);
    out.extend_from_slice(&encode(value)?);
    Ok(())
}

fn write_map(out: &mut Vec<u8>, len: usize) {
    if len < 16 {
        out.push(0x80 | len as u8);
    } else {
        out.push(0xde);
        out.extend_from_slice(&(len as u16).to_be_bytes());
    }
}

fn write_str(out: &mut Vec<u8>, text: &str) {
    let len = text.len();
    if len < 32 {
        out.push(0xa0 | len as u8);
    } else if len < 256 {
        out.push(0xd9);
        out.push(len as u8);
    } else {
        out.push(0xda);
        out.extend_from_slice(&(len as u16).to_be_bytes());
    }
    out.extend_from_slice(text.as_bytes());
}

fn write_uint(out: &mut Vec<u8>, value: u64) {
    if value < 128 {
        out.push(value as u8);
    } else if value < 256 {
        out.push(0xcc);
        out.push(value as u8);
    } else if value < 65536 {
        out.push(0xcd);
        out.extend_from_slice(&(value as u16).to_be_bytes());
    } else if value < 4294967296 {
        out.push(0xce);
        out.extend_from_slice(&(value as u32).to_be_bytes());
    } else {
        out.push(0xcf);
        out.extend_from_slice(&value.to_be_bytes());
    }
}

type Checked = std::result::Result<(), &'static str>;

const MAX_MESSAGE: usize = 1024 * 1024;
const MAX_ELEMENTS: usize = 4096;
const MAX_MESSAGE_ELEMENTS: usize = 65536;
const MAX_TEXT: usize = 65535;

// Values an Unreal client would refuse to read: the glue keeps them out of watched fields, replies and accepted params.
trait Wire {
    fn check(&self) -> Checked;

    // Elements of every list, set and map in the value, nested ones included, a map entry once: as an Unreal client counts them.
    fn elements(&self) -> usize {
        0
    }
}

// How two set elements or map keys compare in Unreal, where text ignores case.
trait WireKey: Ord {
    fn folded(&self) -> Option<String> {
        None
    }
}

macro_rules! wire_always_ok {
    ($($t:ty),*) => {
        $(impl Wire for $t {
            fn check(&self) -> Checked {
                Ok(())
            }
        })*
    };
}
wire_always_ok!(bool, i8, i16, i32, i64, u8, u16, u32, u64);

macro_rules! wire_key_exact {
    ($($t:ty),*) => {
        $(impl WireKey for $t {})*
    };
}
wire_key_exact!(i8, i16, i32, i64, u8, u16, u32, u64);

impl Wire for f32 {
    fn check(&self) -> Checked {
        if self.is_finite() { Ok(()) } else { Err("a number is not finite") }
    }
}

impl Wire for f64 {
    fn check(&self) -> Checked {
        if self.is_finite() { Ok(()) } else { Err("a number is not finite") }
    }
}

impl Wire for String {
    fn check(&self) -> Checked {
        if self.len() <= MAX_TEXT { Ok(()) } else { Err("a text is longer than 65535 bytes") }
    }
}

impl WireKey for String {
    // Unreal keys two texts as one when they have the same length and the same compared part.
    fn folded(&self) -> Option<String> {
        Some(format!("{}\0{}", compared_part(self), utf16_len(self)))
    }
}

impl<T: Wire> Wire for Option<T> {
    fn check(&self) -> Checked {
        match self {
            Some(value) => value.check(),
            None => Ok(()),
        }
    }

    fn elements(&self) -> usize {
        self.as_ref().map_or(0, Wire::elements)
    }
}

impl<T: Wire> Wire for Vec<T> {
    fn check(&self) -> Checked {
        if self.len() > MAX_ELEMENTS {
            return Err("a list has more than 4096 elements");
        }
        self.iter().try_for_each(|value| value.check())
    }

    fn elements(&self) -> usize {
        self.len() + self.iter().map(Wire::elements).sum::<usize>()
    }
}

impl<T: Wire + WireKey> Wire for BTreeSet<T> {
    fn check(&self) -> Checked {
        if self.len() > MAX_ELEMENTS {
            return Err("a set has more than 4096 elements");
        }
        self.iter().try_for_each(|value| value.check())?;
        check_folded(self.iter())
    }

    fn elements(&self) -> usize {
        self.len()
    }
}

impl<K: Wire + WireKey, V: Wire> Wire for BTreeMap<K, V> {
    fn check(&self) -> Checked {
        if self.len() > MAX_ELEMENTS {
            return Err("a map has more than 4096 entries");
        }
        self.keys().try_for_each(|key| key.check())?;
        self.values().try_for_each(|value| value.check())?;
        check_folded(self.keys())
    }

    fn elements(&self) -> usize {
        self.len() + self.values().map(Wire::elements).sum::<usize>()
    }
}

fn check_folded<'a, K: WireKey + 'a>(keys: impl Iterator<Item = &'a K>) -> Checked {
    let mut seen = BTreeSet::new();
    for key in keys {
        let Some(folded) = key.folded() else {
            return Ok(());
        };
        if !seen.insert(folded) {
            return Err("two keys are one key in Unreal, which ignores the case of ASCII letters");
        }
    }
    Ok(())
}

fn unsendable(what: &str, why: &str) -> Error {
    Error::new(&format!("the change was not kept: {what}: {why}"))
}

// Refuses a read until server code replaces the value, such as one restored from a save that players cannot read.
fn unreadable((field, why): (&str, &str)) -> Error {
    Error::new(&format!("unreadable: {field}: the server state holds a value players cannot read: {why}"))
}

fn encode_reply<T: Serialize + Wire>(reply: &T) -> Result<Vec<u8>> {
    Wire::check(reply).map_err(|why| unsendable("the reply", why))?;
    if reply.elements() > MAX_MESSAGE_ELEMENTS {
        return Err(unsendable("the reply", "it holds more than 65536 elements"));
    }
    let bytes = encode(reply)?;
    if bytes.len() > MAX_MESSAGE {
        return Err(unsendable("the reply", "it is larger than 1 MiB"));
    }
    Ok(bytes)
}

const MIN_DATE_MS: i64 = -62135596800000;
const MAX_DATE_MS: i64 = 253402300799999;
const MIN_TIMESPAN_MS: i64 = -922337203685477;
const MAX_TIMESPAN_MS: i64 = 922337203685477;
const MAX_NAME: usize = 1023;

// Unreal holds text as UTF-16, so it counts a text's length in UTF-16 units.
fn utf16_len(text: &str) -> usize {
    text.chars().map(char::len_utf16).sum()
}

// What Unreal compares of a text: the part before any NUL, ignoring the case of ASCII letters only.
fn compared_part(text: &str) -> String {
    text.split('\0').next().unwrap_or("").to_ascii_lowercase()
}

fn check_name(text: &str) -> Checked {
    if utf16_len(text) <= MAX_NAME { Ok(()) } else { Err("a name is longer than 1023 characters") }
}

// Unreal names that differ only in ASCII case or after a NUL are one name, and an empty name is None.
fn check_name_keys<'a>(keys: impl Iterator<Item = &'a String>) -> Checked {
    let mut seen = BTreeSet::new();
    for key in keys {
        let part = compared_part(key);
        if !seen.insert(if part.is_empty() { String::from("none") } else { part }) {
            return Err("two names are one name in Unreal, which ignores the case of ASCII letters and reads an empty name as None");
        }
    }
    Ok(())
}

// Whether a tag exists only the client knows; one this long cannot.
fn check_tag(text: &str) -> Checked {
    if utf16_len(text) <= MAX_NAME { Ok(()) } else { Err("a gameplay tag is longer than 1023 characters") }
}

// The forms FGuid::Parse reads besides its Base64 and Base36 ones, # standing for a hex digit.
const GUID_FORMS: [&str; 6] = [
    "################################",
    "########-####-####-####-############",
    "{########-####-####-####-############}",
    "(########-####-####-####-############)",
    "########-########-########-########",
    "{0x########,0x####,0x####,{0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##}}",
];

fn check_guid(text: &str) -> Checked {
    let bytes = text.as_bytes();
    let fits = |form: &&str| {
        form.len() == bytes.len() && form.bytes().zip(bytes).all(|(want, got)| if want == b'#' { got.is_ascii_hexdigit() } else { *got == want })
    };
    let base64 = bytes.len() == 22 && bytes.iter().all(|got| got.is_ascii_alphanumeric() || b"+/-_".contains(got));
    let base36 = bytes.len() == 25 && bytes.iter().all(|got| got.is_ascii_digit() || got.is_ascii_uppercase());
    if base64 || base36 || GUID_FORMS.iter().any(fits) { Ok(()) } else { Err("a GUID is not in a form Unreal reads") }
}

// FPackageName::IsValidObjectPath, less its check that the path's root is mounted, which only the client knows.
fn check_path(text: &str) -> Checked {
    if utf16_len(text) > MAX_NAME {
        return Err("an object path is longer than 1023 characters");
    }
    let (package, object) = text.split_once('.').unwrap_or((text, ""));
    let package_ok = utf16_len(package) >= 4 && package.starts_with('/') && !package.ends_with('/') && !package.contains("//")
        && !package.contains(|c: char| "\\:*?\"<>|' ,.&!~\n\r\t@#".contains(c));
    let object_ok = !object.contains(|c: char| "\"' ,|&!~\n\r\t@#(){}[]=;^%$`/".contains(c)) && !object.ends_with(':');
    if text.is_empty() || (package_ok && object_ok && !text.ends_with('.')) { Ok(()) } else { Err("a text is not an object path") }
}

fn check_date(ms: &i64) -> Checked {
    if (MIN_DATE_MS..=MAX_DATE_MS).contains(ms) { Ok(()) } else { Err("a date is outside the years 1 to 9999") }
}

fn check_timespan(ms: &i64) -> Checked {
    if (MIN_TIMESPAN_MS..=MAX_TIMESPAN_MS).contains(ms) { Ok(()) } else { Err("a timespan is longer than Unreal holds") }
}

impl Wire for CrowdyExecTestPhase {
    fn check(&self) -> Checked {
        Ok(())
    }
}

impl WireKey for CrowdyExecTestPhase {}

impl Wire for Vector {
    fn check(&self) -> Checked {
        Wire::check(&self.X)?;
        Wire::check(&self.Y)?;
        Wire::check(&self.Z)?;
        Ok(())
    }
}

impl Wire for Vector2D {
    fn check(&self) -> Checked {
        Wire::check(&self.X)?;
        Wire::check(&self.Y)?;
        Ok(())
    }
}

impl Wire for IntPoint {
    fn check(&self) -> Checked {
        Wire::check(&self.X)?;
        Wire::check(&self.Y)?;
        Ok(())
    }
}

impl Wire for IntVector {
    fn check(&self) -> Checked {
        Wire::check(&self.X)?;
        Wire::check(&self.Y)?;
        Wire::check(&self.Z)?;
        Ok(())
    }
}

impl Wire for Rotator {
    fn check(&self) -> Checked {
        Wire::check(&self.Pitch)?;
        Wire::check(&self.Yaw)?;
        Wire::check(&self.Roll)?;
        Ok(())
    }
}

impl Wire for Quat {
    fn check(&self) -> Checked {
        Wire::check(&self.X)?;
        Wire::check(&self.Y)?;
        Wire::check(&self.Z)?;
        Wire::check(&self.W)?;
        Ok(())
    }
}

impl Wire for LinearColor {
    fn check(&self) -> Checked {
        Wire::check(&self.R)?;
        Wire::check(&self.G)?;
        Wire::check(&self.B)?;
        Wire::check(&self.A)?;
        Ok(())
    }
}

impl Wire for Color {
    fn check(&self) -> Checked {
        Wire::check(&self.R)?;
        Wire::check(&self.G)?;
        Wire::check(&self.B)?;
        Wire::check(&self.A)?;
        Ok(())
    }
}

impl Wire for CrowdyExecTestBossState {
    fn check(&self) -> Checked {
        Wire::check(&self.Health)?;
        Wire::check(&self.bDefeated)?;
        Wire::check(&self.Phase)?;
        Wire::check(&self.Secret)?;
        Ok(())
    }
}

impl Wire for CrowdyExecTestScalars {
    fn check(&self) -> Checked {
        Wire::check(&self.bDefeated)?;
        Wire::check(&self.Health)?;
        Wire::check(&self.Level)?;
        Wire::check(&self.Big)?;
        Wire::check(&self.Speed)?;
        Wire::check(&self.Precise)?;
        Wire::check(&self.Name)?;
        Wire::check(&self.Phase)?;
        Ok(())
    }
}

impl Wire for CrowdyExecTestContainers {
    fn check(&self) -> Checked {
        Wire::check(&self.Hits)?;
        Wire::check(&self.Tags)?;
        Wire::check(&self.DamageByPlayer)?;
        Wire::check(&self.Bytes)?;
        Ok(())
    }

    fn elements(&self) -> usize {
        self.Hits.elements() + self.Tags.elements() + self.DamageByPlayer.elements() + self.Bytes.elements()
    }
}

impl Wire for CrowdyExecTestEngine {
    fn check(&self) -> Checked {
        Wire::check(&self.Arena)?;
        Wire::check(&self.When).and_then(|()| check_date(&self.When))?;
        Wire::check(&self.Id).and_then(|()| check_guid(&self.Id))?;
        Wire::check(&self.Maybe)?;
        Ok(())
    }
}

impl Wire for CrowdyExecTestExtras {
    fn check(&self) -> Checked {
        Wire::check(&self.Small)?;
        Wire::check(&self.Tiny)?;
        Wire::check(&self.Huge)?;
        Wire::check(&self.Rotation)?;
        Wire::check(&self.Orientation)?;
        Wire::check(&self.Tint)?;
        Wire::check(&self.Color)?;
        Wire::check(&self.Cell)?;
        Wire::check(&self.Block)?;
        Wire::check(&self.Offset)?;
        Wire::check(&self.Cooldown).and_then(|()| check_timespan(&self.Cooldown))?;
        Wire::check(&self.Tag).and_then(|()| check_tag(&self.Tag))?;
        Wire::check(&self.Mesh).and_then(|()| check_path(&self.Mesh))?;
        Wire::check(&self.Class).and_then(|()| check_path(&self.Class))?;
        Wire::check(&self.Path).and_then(|()| check_path(&self.Path))?;
        Wire::check(&self.ByIndex)?;
        Wire::check(&self.Phases)?;
        Wire::check(&self.Attacks)?;
        Wire::check(&self.Notes)?;
        Ok(())
    }

    fn elements(&self) -> usize {
        self.ByIndex.elements() + self.Phases.elements() + self.Attacks.elements() + self.Notes.elements()
    }
}

impl Wire for CrowdyExecTestKeys {
    fn check(&self) -> Checked {
        Wire::check(&self.HitByPhase)?;
        Wire::check(&self.PhaseList)?;
        Wire::check(&self.MaybePhase)?;
        Wire::check(&self.ByName).and_then(|()| self.ByName.iter().try_for_each(|(k, _)| check_name(&k)).and_then(|()| check_name_keys(self.ByName.keys())))?;
        Ok(())
    }

    fn elements(&self) -> usize {
        self.HitByPhase.elements() + self.PhaseList.elements() + self.ByName.elements()
    }
}

impl Wire for CrowdyExecTestRaw {
    fn check(&self) -> Checked {
        Wire::check(&self.r#type)?;
        Ok(())
    }
}

impl Wire for CrowdyExecTestHit {
    fn check(&self) -> Checked {
        Wire::check(&self.Damage)?;
        Wire::check(&self.Source).and_then(|()| check_name(&self.Source))?;
        Ok(())
    }
}

ckx_sdk::export_hub!(ServerObject);
