// The Server Object type ck_exec_fixture's structs, generated by the Crowdy SDK from its definition. Regenerate it; do not edit.
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum CrowdyExecTestPhase {
    Calm,
    Enraged,
    Final,
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct Vector {
    pub X: f64, // Double
    pub Y: f64, // Double
    pub Z: f64, // Double
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct Vector2D {
    pub X: f64, // Double
    pub Y: f64, // Double
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct IntPoint {
    pub X: i32, // Int32
    pub Y: i32, // Int32
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct IntVector {
    pub X: i32, // Int32
    pub Y: i32, // Int32
    pub Z: i32, // Int32
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct Rotator {
    pub Pitch: f64, // Double
    pub Yaw: f64, // Double
    pub Roll: f64, // Double
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct Quat {
    pub X: f64, // Double
    pub Y: f64, // Double
    pub Z: f64, // Double
    pub W: f64, // Double
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct LinearColor {
    pub R: f32, // Float
    pub G: f32, // Float
    pub B: f32, // Float
    pub A: f32, // Float
}

#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Debug, Default)]
#[serde(default)]
pub struct Color {
    pub R: u8, // UInt8
    pub G: u8, // UInt8
    pub B: u8, // UInt8
    pub A: u8, // UInt8
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestBossState {
    pub Health: i32, // Int32
    pub bDefeated: bool, // Bool
    pub Phase: CrowdyExecTestPhase, // Enum CrowdyExecTestPhase
    pub Secret: i32, // Int32
}

impl Default for CrowdyExecTestBossState {
    fn default() -> Self {
        Self {
            Health: 4000,
            bDefeated: false,
            Phase: CrowdyExecTestPhase::Calm,
            Secret: 0,
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestScalars {
    pub bDefeated: bool, // Bool
    pub Health: i32, // Int32
    pub Level: i32, // Int32
    pub Big: i64, // Int64
    pub Speed: f32, // Float
    pub Precise: f64, // Double
    pub Name: String, // String
    pub Phase: CrowdyExecTestPhase, // Enum CrowdyExecTestPhase
}

impl Default for CrowdyExecTestScalars {
    fn default() -> Self {
        Self {
            bDefeated: false,
            Health: 0,
            Level: 0,
            Big: 0,
            Speed: 0.0,
            Precise: 0.0,
            Name: String::new(),
            Phase: CrowdyExecTestPhase::Calm,
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestContainers {
    pub Hits: Vec<i32>, // Array<Int32>
    pub Tags: BTreeSet<String>, // Set<String>
    pub DamageByPlayer: BTreeMap<String, i32>, // Map<String, Int32>
    pub Bytes: Vec<u8>, // Array<UInt8>
}

impl Default for CrowdyExecTestContainers {
    fn default() -> Self {
        Self {
            Hits: Vec::new(),
            Tags: BTreeSet::new(),
            DamageByPlayer: BTreeMap::new(),
            Bytes: Vec::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestEngine {
    pub Arena: Vector, // Vector
    pub When: i64, // DateTime
    pub Id: String, // Guid
    pub Maybe: Option<i32>, // Optional<Int32>
}

impl Default for CrowdyExecTestEngine {
    fn default() -> Self {
        Self {
            Arena: Vector { X: 0.0, Y: 0.0, Z: 0.0 },
            When: -62135596800000,
            Id: String::from("00000000000000000000000000000000"),
            Maybe: None,
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestExtras {
    pub Small: u8, // UInt8
    pub Tiny: i8, // Int8
    pub Huge: u64, // UInt64
    pub Rotation: Rotator, // Rotator
    pub Orientation: Quat, // Quat
    pub Tint: LinearColor, // LinearColor
    pub Color: Color, // Color
    pub Cell: IntPoint, // IntPoint
    pub Block: IntVector, // IntVector
    pub Offset: Vector2D, // Vector2D
    pub Cooldown: i64, // Timespan
    pub Tag: String, // GameplayTag
    pub Mesh: String, // SoftPath
    pub Class: String, // SoftPath
    pub Path: String, // SoftPath
    pub ByIndex: BTreeMap<i32, String>, // Map<Int32, String>
    pub Phases: BTreeSet<CrowdyExecTestPhase>, // Set<Enum CrowdyExecTestPhase>
    pub Attacks: Vec<CrowdyExecTestHit>, // Array<Struct CrowdyExecTestHit>
    pub Notes: Vec<String>, // Array<String>
}

impl Default for CrowdyExecTestExtras {
    fn default() -> Self {
        Self {
            Small: 0,
            Tiny: 0,
            Huge: 0,
            Rotation: Rotator { Pitch: 0.0, Yaw: 0.0, Roll: 0.0 },
            Orientation: Quat { X: 0.0, Y: 0.0, Z: 0.0, W: 1.0 },
            Tint: LinearColor { R: 1.0, G: 1.0, B: 1.0, A: 1.0 },
            Color: Color { R: 255, G: 255, B: 255, A: 255 },
            Cell: IntPoint { X: 0, Y: 0 },
            Block: IntVector { X: 0, Y: 0, Z: 0 },
            Offset: Vector2D { X: 0.0, Y: 0.0 },
            Cooldown: 0,
            Tag: String::new(),
            Mesh: String::new(),
            Class: String::new(),
            Path: String::new(),
            ByIndex: BTreeMap::new(),
            Phases: BTreeSet::new(),
            Attacks: Vec::new(),
            Notes: Vec::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestKeys {
    pub HitByPhase: BTreeMap<CrowdyExecTestPhase, CrowdyExecTestHit>, // Map<Enum CrowdyExecTestPhase, Struct CrowdyExecTestHit>
    pub PhaseList: Vec<CrowdyExecTestPhase>, // Array<Enum CrowdyExecTestPhase>
    pub MaybePhase: Option<CrowdyExecTestPhase>, // Optional<Enum CrowdyExecTestPhase>
    pub ByName: BTreeMap<String, i32>, // Map<Name, Int32>
}

impl Default for CrowdyExecTestKeys {
    fn default() -> Self {
        Self {
            HitByPhase: BTreeMap::new(),
            PhaseList: Vec::new(),
            MaybePhase: None,
            ByName: BTreeMap::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestRaw {
    pub r#type: String, // String
}

impl Default for CrowdyExecTestRaw {
    fn default() -> Self {
        Self {
            r#type: String::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
#[serde(default)]
pub struct CrowdyExecTestHit {
    pub Damage: i32, // Int32
    pub Source: String, // Name
}

impl Default for CrowdyExecTestHit {
    fn default() -> Self {
        Self {
            Damage: 0,
            Source: String::new(),
        }
    }
}
